blank_issues_enabled: false
contact_links:
  - name: 💬 Questions & Feedback
    url: https://github.com/Xronni/spotify-mini-player/discussions
    about: Ask questions, share ideas, and chat with the author.
